"""
Curated Catalog Seed Data for DroneCraft.
Includes 60+ real-world verified drone components across all 5 powertrain categories.
"""

SEED_FRAMES = [
    {
        "name": "TBS Source One V5 5\"",
        "manufacturer": "Team BlackSheep",
        "wheelbase_mm": 226.0,
        "frame_type": "Quad-X",
        "max_prop_size_inch": 5.1,
        "dry_weight_g": 125.0,
        "payload_volume_cm3": 180.0,
        "price_usd": 29.95,
        "source_url": "https://www.team-blacksheep.com",
        "image_url": "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=400&q=80"
    },
    {
        "name": "iFlight Nazgul Evoque F5X V2",
        "manufacturer": "iFlight",
        "wheelbase_mm": 223.0,
        "frame_type": "Quad-X",
        "max_prop_size_inch": 5.1,
        "dry_weight_g": 166.0,
        "payload_volume_cm3": 210.0,
        "price_usd": 74.99,
        "source_url": "https://iflight-rc.com",
        "image_url": "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=400&q=80"
    },
    {
        "name": "GEPRC CineLog35 V2 HD",
        "manufacturer": "GEPRC",
        "wheelbase_mm": 142.0,
        "frame_type": "Cinewhoop",
        "max_prop_size_inch": 3.5,
        "dry_weight_g": 115.0,
        "payload_volume_cm3": 140.0,
        "price_usd": 49.99,
        "source_url": "https://geprc.com",
        "image_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80"
    },
    {
        "name": "iFlight Chimera7 Pro V2 7.5\"",
        "manufacturer": "iFlight",
        "wheelbase_mm": 321.0,
        "frame_type": "Long-range",
        "max_prop_size_inch": 7.5,
        "dry_weight_g": 248.0,
        "payload_volume_cm3": 350.0,
        "price_usd": 99.99,
        "source_url": "https://iflight-rc.com",
        "image_url": "https://images.unsplash.com/photo-1506947411487-a56738267384?w=400&q=80"
    },
    {
        "name": "Holybro X500 V2 Professional Kit",
        "manufacturer": "Holybro",
        "wheelbase_mm": 500.0,
        "frame_type": "Quad-X",
        "max_prop_size_inch": 10.5,
        "dry_weight_g": 460.0,
        "payload_volume_cm3": 850.0,
        "price_usd": 159.00,
        "source_url": "https://holybro.com",
        "image_url": "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400&q=80"
    },
    {
        "name": "Tarot 650 Iron Man Carbon Hexa",
        "manufacturer": "Tarot",
        "wheelbase_mm": 650.0,
        "frame_type": "Hex-X",
        "max_prop_size_inch": 15.0,
        "dry_weight_g": 680.0,
        "payload_volume_cm3": 1200.0,
        "price_usd": 189.99,
        "source_url": "https://tarot-rc.com",
        "image_url": "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=400&q=80"
    },
    {
        "name": "SpeedyBee Mario 5 DC",
        "manufacturer": "SpeedyBee",
        "wheelbase_mm": 227.0,
        "frame_type": "Quad-X",
        "max_prop_size_inch": 5.1,
        "dry_weight_g": 129.0,
        "payload_volume_cm3": 190.0,
        "price_usd": 42.99,
        "source_url": "https://speedybee.com",
        "image_url": "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=400&q=80"
    },
    {
        "name": "Flywoo Explorer LR 4 V2",
        "manufacturer": "Flywoo",
        "wheelbase_mm": 168.0,
        "frame_type": "Long-range",
        "max_prop_size_inch": 4.0,
        "dry_weight_g": 62.0,
        "payload_volume_cm3": 95.0,
        "price_usd": 38.99,
        "source_url": "https://flywoo.net",
        "image_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80"
    },
    {
        "name": "ApexDC 5\" Freestyle Frame",
        "manufacturer": "ImpulseRC",
        "wheelbase_mm": 225.0,
        "frame_type": "Quad-X",
        "max_prop_size_inch": 5.2,
        "dry_weight_g": 138.0,
        "payload_volume_cm3": 175.0,
        "price_usd": 95.00,
        "source_url": "https://impulserc.com",
        "image_url": "https://images.unsplash.com/photo-1506947411487-a56738267384?w=400&q=80"
    },
    {
        "name": "Gryphon Dynamics X8 1000 Heavy Lifter",
        "manufacturer": "Gryphon Dynamics",
        "wheelbase_mm": 1000.0,
        "frame_type": "Octo-X",
        "max_prop_size_inch": 18.0,
        "dry_weight_g": 1450.0,
        "payload_volume_cm3": 3500.0,
        "price_usd": 890.00,
        "source_url": "https://gryphondynamics.com",
        "image_url": "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=400&q=80"
    }
]

SEED_MOTORS = [
    {
        "model": "T-Motor F60 PRO V 1950KV",
        "manufacturer": "T-Motor",
        "kv": 1950.0,
        "stator_size": "2207.5",
        "internal_resistance_mohm": 48.0,
        "idle_current_a": 1.1,
        "max_continuous_current_a": 46.5,
        "max_power_w": 1100.0,
        "recommended_voltage_s_min": 4,
        "recommended_voltage_s_max": 6,
        "weight_g": 33.8,
        "price_usd": 27.90
    },
    {
        "model": "EMAX ECO II 2207 2400KV 4S",
        "manufacturer": "EMAX",
        "kv": 2400.0,
        "stator_size": "2207",
        "internal_resistance_mohm": 52.0,
        "idle_current_a": 1.4,
        "max_continuous_current_a": 42.0,
        "max_power_w": 690.0,
        "recommended_voltage_s_min": 3,
        "recommended_voltage_s_max": 4,
        "weight_g": 32.5,
        "price_usd": 15.99
    },
    {
        "model": "iFlight XING2 2207 1855KV 6S",
        "manufacturer": "iFlight",
        "kv": 1855.0,
        "stator_size": "2207",
        "internal_resistance_mohm": 55.0,
        "idle_current_a": 0.95,
        "max_continuous_current_a": 40.2,
        "max_power_w": 965.0,
        "recommended_voltage_s_min": 5,
        "recommended_voltage_s_max": 6,
        "weight_g": 31.6,
        "price_usd": 23.99
    },
    {
        "model": "BrotherHobby Avenger 2806.5 1300KV",
        "manufacturer": "BrotherHobby",
        "kv": 1300.0,
        "stator_size": "2806.5",
        "internal_resistance_mohm": 42.0,
        "idle_current_a": 1.2,
        "max_continuous_current_a": 48.0,
        "max_power_w": 1250.0,
        "recommended_voltage_s_min": 4,
        "recommended_voltage_s_max": 6,
        "weight_g": 46.5,
        "price_usd": 29.99
    },
    {
        "model": "Flywoo NIN V2 1404 2750KV",
        "manufacturer": "Flywoo",
        "kv": 2750.0,
        "stator_size": "1404",
        "internal_resistance_mohm": 165.0,
        "idle_current_a": 0.35,
        "max_continuous_current_a": 14.5,
        "max_power_w": 230.0,
        "recommended_voltage_s_min": 3,
        "recommended_voltage_s_max": 4,
        "weight_g": 9.5,
        "price_usd": 16.99
    },
    {
        "model": "SPEEDYBEE 2207 2050KV 6S",
        "manufacturer": "SpeedyBee",
        "kv": 2050.0,
        "stator_size": "2207",
        "internal_resistance_mohm": 58.0,
        "idle_current_a": 1.05,
        "max_continuous_current_a": 38.0,
        "max_power_w": 890.0,
        "recommended_voltage_s_min": 4,
        "recommended_voltage_s_max": 6,
        "weight_g": 32.2,
        "price_usd": 17.50
    },
    {
        "model": "Holybro 2216 880KV V2",
        "manufacturer": "Holybro",
        "kv": 880.0,
        "stator_size": "2216",
        "internal_resistance_mohm": 95.0,
        "idle_current_a": 0.6,
        "max_continuous_current_a": 22.0,
        "max_power_w": 380.0,
        "recommended_voltage_s_min": 3,
        "recommended_voltage_s_max": 4,
        "weight_g": 68.0,
        "price_usd": 24.50
    },
    {
        "model": "Sunnysky V3508 380KV Heavy Motor",
        "manufacturer": "Sunnysky",
        "kv": 380.0,
        "stator_size": "3508",
        "internal_resistance_mohm": 115.0,
        "idle_current_a": 0.4,
        "max_continuous_current_a": 18.0,
        "max_power_w": 420.0,
        "recommended_voltage_s_min": 4,
        "recommended_voltage_s_max": 6,
        "weight_g": 108.0,
        "price_usd": 36.00
    },
    {
        "model": "T-Motor U8 II 100KV Heavy Lifter",
        "manufacturer": "T-Motor",
        "kv": 100.0,
        "stator_size": "8120",
        "internal_resistance_mohm": 110.0,
        "idle_current_a": 0.8,
        "max_continuous_current_a": 42.0,
        "max_power_w": 2200.0,
        "recommended_voltage_s_min": 6,
        "recommended_voltage_s_max": 12,
        "weight_g": 240.0,
        "price_usd": 185.00
    },
    {
        "model": "GEPRC SPEEDX2 2105.5 2650KV",
        "manufacturer": "GEPRC",
        "kv": 2650.0,
        "stator_size": "2105.5",
        "internal_resistance_mohm": 82.0,
        "idle_current_a": 0.7,
        "max_continuous_current_a": 28.0,
        "max_power_w": 460.0,
        "recommended_voltage_s_min": 4,
        "recommended_voltage_s_max": 4,
        "weight_g": 21.5,
        "price_usd": 21.99
    }
]

SEED_PROPELLERS = [
    {
        "model": "HQProp Ethix S3 Watermelon 5x3.1x3",
        "manufacturer": "HQProp",
        "diameter_inch": 5.0,
        "pitch_inch": 3.1,
        "blade_count": 3,
        "weight_g": 3.6,
        "ct_hover": 0.088,
        "cp_hover": 0.041,
        "material": "Polycarbonate",
        "price_usd": 3.50
    },
    {
        "model": "Gemfan Hurricane 51466 V2 Tri-Blade",
        "manufacturer": "Gemfan",
        "diameter_inch": 5.1,
        "pitch_inch": 4.66,
        "blade_count": 3,
        "weight_g": 4.2,
        "ct_hover": 0.108,
        "cp_hover": 0.058,
        "material": "Polycarbonate",
        "price_usd": 3.75
    },
    {
        "model": "HQProp CineLog 3535 Tri-Blade 3.5\"",
        "manufacturer": "HQProp",
        "diameter_inch": 3.5,
        "pitch_inch": 3.5,
        "blade_count": 3,
        "weight_g": 2.2,
        "ct_hover": 0.092,
        "cp_hover": 0.045,
        "material": "Polycarbonate",
        "price_usd": 3.20
    },
    {
        "model": "Gemfan Flash 7040 3-Blade 7\"",
        "manufacturer": "Gemfan",
        "diameter_inch": 7.0,
        "pitch_inch": 4.0,
        "blade_count": 3,
        "weight_g": 7.9,
        "ct_hover": 0.098,
        "cp_hover": 0.051,
        "material": "Polycarbonate",
        "price_usd": 4.80
    },
    {
        "model": "HQProp Micro 4x2.5x2 Bi-Blade",
        "manufacturer": "HQProp",
        "diameter_inch": 4.0,
        "pitch_inch": 2.5,
        "blade_count": 2,
        "weight_g": 1.4,
        "ct_hover": 0.065,
        "cp_hover": 0.026,
        "material": "Polycarbonate",
        "price_usd": 2.80
    },
    {
        "model": "APC 10x4.5 Multi-Rotor Bi-Blade",
        "manufacturer": "APC",
        "diameter_inch": 10.0,
        "pitch_inch": 4.5,
        "blade_count": 2,
        "weight_g": 13.5,
        "ct_hover": 0.082,
        "cp_hover": 0.038,
        "material": "Glass Reinforced Nylon",
        "price_usd": 7.50
    },
    {
        "model": "Tarot 15x5.5 High-Efficiency Carbon Fiber",
        "manufacturer": "Tarot",
        "diameter_inch": 15.0,
        "pitch_inch": 5.5,
        "blade_count": 2,
        "weight_g": 24.0,
        "ct_hover": 0.095,
        "cp_hover": 0.042,
        "material": "3K Carbon Fiber",
        "price_usd": 22.00
    },
    {
        "model": "T-Motor Carbon Fiber 18x6.1 Ultra Light",
        "manufacturer": "T-Motor",
        "diameter_inch": 18.0,
        "pitch_inch": 6.1,
        "blade_count": 2,
        "weight_g": 38.0,
        "ct_hover": 0.102,
        "cp_hover": 0.046,
        "material": "Carbon Fiber",
        "price_usd": 48.00
    },
    {
        "model": "DALProp Cyclone T5046C High Pitch 5\"",
        "manufacturer": "DALProp",
        "diameter_inch": 5.0,
        "pitch_inch": 4.6,
        "blade_count": 3,
        "weight_g": 4.5,
        "ct_hover": 0.112,
        "cp_hover": 0.062,
        "material": "Polycarbonate",
        "price_usd": 3.99
    }
]

SEED_ESCS = [
    {
        "model": "SpeedyBee F405 V4 55A 4-in-1",
        "manufacturer": "SpeedyBee",
        "continuous_current_a": 55.0,
        "burst_current_a": 70.0,
        "voltage_min_s": 3,
        "voltage_max_s": 6,
        "protocol": "DShot600",
        "form_factor": "4-in-1",
        "weight_g": 14.5,
        "price_usd": 49.99
    },
    {
        "model": "Foxeer Reaper F4 65A 128K 4-in-1",
        "manufacturer": "Foxeer",
        "continuous_current_a": 65.0,
        "burst_current_a": 85.0,
        "voltage_min_s": 3,
        "voltage_max_s": 8,
        "protocol": "DShot600",
        "form_factor": "4-in-1",
        "weight_g": 16.2,
        "price_usd": 79.90
    },
    {
        "model": "Holybro Tekko32 F4 45A 4-in-1",
        "manufacturer": "Holybro",
        "continuous_current_a": 45.0,
        "burst_current_a": 55.0,
        "voltage_min_s": 3,
        "voltage_max_s": 6,
        "protocol": "DShot1200",
        "form_factor": "4-in-1",
        "weight_g": 12.8,
        "price_usd": 58.50
    },
    {
        "model": "Flywoo GOKU GN405 20A AIO",
        "manufacturer": "Flywoo",
        "continuous_current_a": 20.0,
        "burst_current_a": 25.0,
        "voltage_min_s": 2,
        "voltage_max_s": 4,
        "protocol": "DShot600",
        "form_factor": "4-in-1",
        "weight_g": 6.8,
        "price_usd": 45.00
    },
    {
        "model": "T-Motor F55A PRO II 4-in-1",
        "manufacturer": "T-Motor",
        "continuous_current_a": 55.0,
        "burst_current_a": 75.0,
        "voltage_min_s": 3,
        "voltage_max_s": 6,
        "protocol": "DShot1200",
        "form_factor": "4-in-1",
        "weight_g": 17.5,
        "price_usd": 82.00
    },
    {
        "model": "Hobbywing XRotor Pro 80A HV Single",
        "manufacturer": "Hobbywing",
        "continuous_current_a": 80.0,
        "burst_current_a": 100.0,
        "voltage_min_s": 6,
        "voltage_max_s": 12,
        "protocol": "PWM",
        "form_factor": "Individual",
        "weight_g": 85.0,
        "price_usd": 59.00
    },
    {
        "model": "Holybro 65A Metal 4-in-1 Pro",
        "manufacturer": "Holybro",
        "continuous_current_a": 65.0,
        "burst_current_a": 80.0,
        "voltage_min_s": 4,
        "voltage_max_s": 8,
        "protocol": "DShot1200",
        "form_factor": "4-in-1",
        "weight_g": 18.0,
        "price_usd": 94.00
    }
]

SEED_BATTERIES = [
    {
        "brand": "Tattu",
        "model": "R-Line Version 5.0 6S 1400mAh 150C",
        "cell_chemistry": "LiPo",
        "cells_s": 6,
        "capacity_mah": 1400.0,
        "c_rating_continuous": 150.0,
        "c_rating_burst": 250.0,
        "internal_resistance_cell_mohm": 3.2,
        "nominal_cell_voltage_v": 3.7,
        "weight_g": 222.0,
        "price_usd": 41.99
    },
    {
        "brand": "CNHL",
        "model": "Black Series 4S 1500mAh 100C",
        "cell_chemistry": "LiPo",
        "cells_s": 4,
        "capacity_mah": 1500.0,
        "c_rating_continuous": 100.0,
        "c_rating_burst": 200.0,
        "internal_resistance_cell_mohm": 4.5,
        "nominal_cell_voltage_v": 3.7,
        "weight_g": 182.0,
        "price_usd": 22.99
    },
    {
        "brand": "Tattu",
        "model": "R-Line 4S 1550mAh 120C",
        "cell_chemistry": "LiPo",
        "cells_s": 4,
        "capacity_mah": 1550.0,
        "c_rating_continuous": 120.0,
        "c_rating_burst": 200.0,
        "internal_resistance_cell_mohm": 3.8,
        "nominal_cell_voltage_v": 3.7,
        "weight_g": 178.0,
        "price_usd": 29.99
    },
    {
        "brand": "CNHL",
        "model": "Ministar 6S 1100mAh 100C",
        "cell_chemistry": "LiPo",
        "cells_s": 6,
        "capacity_mah": 1100.0,
        "c_rating_continuous": 100.0,
        "c_rating_burst": 180.0,
        "internal_resistance_cell_mohm": 4.8,
        "nominal_cell_voltage_v": 3.7,
        "weight_g": 188.0,
        "price_usd": 28.50
    },
    {
        "brand": "Molicel",
        "model": "P42A 6S1P 4200mAh 35A Li-ion Long Range",
        "cell_chemistry": "Li-ion",
        "cells_s": 6,
        "capacity_mah": 4200.0,
        "c_rating_continuous": 8.5,
        "c_rating_burst": 12.0,
        "internal_resistance_cell_mohm": 15.0,
        "nominal_cell_voltage_v": 3.6,
        "weight_g": 435.0,
        "price_usd": 59.99
    },
    {
        "brand": "GNB",
        "model": "Gaoneng 4S 850mAh 80C Cinewhoop",
        "cell_chemistry": "LiPo",
        "cells_s": 4,
        "capacity_mah": 850.0,
        "c_rating_continuous": 80.0,
        "c_rating_burst": 160.0,
        "internal_resistance_cell_mohm": 5.5,
        "nominal_cell_voltage_v": 3.7,
        "weight_g": 94.0,
        "price_usd": 18.99
    },
    {
        "brand": "Tattu",
        "model": "Plus Smart 6S 16000mAh 25C Heavy Lift",
        "cell_chemistry": "LiPo",
        "cells_s": 6,
        "capacity_mah": 16000.0,
        "c_rating_continuous": 25.0,
        "c_rating_burst": 50.0,
        "internal_resistance_cell_mohm": 1.8,
        "nominal_cell_voltage_v": 3.7,
        "weight_g": 1930.0,
        "price_usd": 320.00
    },
    {
        "brand": "Sony Murata",
        "model": "VTC6 4S1P 3000mAh 30A Li-ion Micro LR",
        "cell_chemistry": "Li-ion",
        "cells_s": 4,
        "capacity_mah": 3000.0,
        "c_rating_continuous": 10.0,
        "c_rating_burst": 15.0,
        "internal_resistance_cell_mohm": 18.0,
        "nominal_cell_voltage_v": 3.6,
        "weight_g": 200.0,
        "price_usd": 34.00
    }
]
